### ISSUE TITLE
Subdelimiter does not appear to be splitting on fields that allow multiple values

### ISSUE THREAD

**Issue by ruebot** [mjordan/islandora_workbench#121]
A pipe or anything else I define as a subdelimiter is not working for me.

It is failing in a variety of different field types:
  - Entity reference: `33 | 34`
  - Text (plain): `http://some.url | http://some.other.url`
  - Text (formatted, long): `"Some long text with a \r or , or %. | So other long text \n $ AMPERSAND!"`

My experiment testing below.

tl;dr

- Control (no pipes) :heavy_check_mark: success!
- Entity :x: 422 error
- Longtext :yellow_square: import successful, but does not split
- Text :yellow_square: import successful, but does not split

## Control :heavy_check_mark: 

control.csv

```csv
"field_pid","file","field_member_of","field_display_hints","id","field_model","title","field_extent","field_genre","field_edtf_date","field_linked_agent","field_subject","field_language","field_rights","field_note","field_identifier","field_local_identifier","field_resource_type"
"yul:1127652","yul_1127652.tif",15,2,1127680,25,"Montage workshop. no.29","1 photograph : b&w negative ; 35 mm.",32,1981,"relators:pht:31",33,38,"http://rightsstatements.org/vocab/InC/1.0/","Holding: Original in the custody of creator.","29 CERLAC","0029CERLAC",12
```

config.yml
```yml
task: create
host: "http://omega.library.yorku.ca"
username: admin
password: no
content_type: islandora_object
input_dir: /home/nruest/Projects/york/test-content/workbench-pipe-issue/control
input_csv: control.csv
media_use_tid: 17
drupal_filesystem: "fedora://"
delimiter: ","
subdelimiter: "|"
id_field: id
log_file_path: control.log
media_types:
  - file: ['tif', 'tiff', 'jp2', 'zip', 'tar']
  - document: ['pdf', 'doc', 'docx', 'ppt', 'pptx']
  - image: ['png', 'gif', 'jpg', 'jpeg']
  - audio: ['mp3', 'wav', 'aac']
  - video: ['mp4']
  - extracted_text: ['txt']
```

check
```
$ ./workbench --config config.yml --check
OK, http://omega.library.yorku.ca is accessible using the credentials provided.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /home/nruest/Projects/york/test-content/workbench-pipe-issue/control/control.csv found.
OK, all 1 rows in the CSV file have the same number of columns as there are headers (18).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, term IDs/names in CSV file exist in their respective taxonomies.
OK, files named in the CSV "file" column are all
```

run
```
$ ./workbench --config config.yml
Node for "Montage workshop. no.29" (record 1127680) created at http://omega.library.yorku.ca/node/148.
+File media for yul_1127652.tif created.
```

log
```
07-Oct-20 08:05:09 - INFO - Starting configuration check for "create" task using config file config.yml.
07-Oct-20 08:05:11 - INFO - http://omega.library.yorku.ca is accessible using the credentials provided.
07-Oct-20 08:05:11 - INFO - OK, configuration file has all required values (did not check for optional values).
07-Oct-20 08:05:11 - INFO - OK, CSV file /home/nruest/Projects/york/test-content/workbench-pipe-issue/control/control.csv found.
07-Oct-20 08:05:11 - INFO - OK, all 1 rows in the CSV file have the same number of columns as there are headers (18).
07-Oct-20 08:05:13 - INFO - OK, CSV column headers match Drupal field names.
07-Oct-20 08:05:13 - INFO - OK, required Drupal fields are present in the CSV file.
07-Oct-20 08:05:15 - INFO - OK, term IDs/names in CSV file exist in their respective taxonomies.
07-Oct-20 08:05:16 - INFO - OK, files named in the CSV "file" column are all present.
07-Oct-20 08:05:16 - INFO - Configuration checked for "create" task using config file config.yml, no problems found.
07-Oct-20 08:05:30 - INFO - "Create" task started using config file config.yml
07-Oct-20 08:05:32 - INFO - Node for Montage workshop. no.29 (record 1127680) created at http://omega.library.yorku.ca/node/148.
07-Oct-20 08:06:26 - INFO - Media (file) created at http://omega.library.yorku.ca/media/404, linked to node http://omega.library.yorku.ca/node/148.
07-Oct-20 08:06:26 - INFO - File media for yul_1127652.tif created.
```

## Entity :x:

entity.csv
```csv
"field_pid","file","field_member_of","field_display_hints","id","field_model","title","field_extent","field_genre","field_edtf_date","field_linked_agent","field_subject","field_language","field_rights","field_note","field_identifier","field_local_identifier","field_resource_type"
"yul:1127652","yul_1127652.tif",15,2,1127680,25,"Montage workshop. no.29","1 photograph : b&w negative ; 35 mm.",32,1981,"relators:pht:31","33 | 34",38,"http://rightsstatements.org/vocab/InC/1.0/","Holding: Original in the custody of creator.","29 CERLAC","0029CERLAC",12
```

config.yml
```
task: create
host: "http://omega.library.yorku.ca"
username: admin
password: no
content_type: islandora_object
input_dir: /home/nruest/Projects/york/test-content/workbench-pipe-issue/entity
input_csv: entity.csv
media_use_tid: 17
drupal_filesystem: "fedora://"
delimiter: ","
subdelimiter: "|"
id_field: id
log_file_path: entity.log
media_types:
  - file: ['tif', 'tiff', 'jp2', 'zip', 'tar']
  - document: ['pdf', 'doc', 'docx', 'ppt', 'pptx']
  - image: ['png', 'gif', 'jpg', 'jpeg']
  - audio: ['mp3', 'wav', 'aac']
  - video: ['mp4']
  - extracted_text: ['txt']
```

check
```
$ ./workbench --config config.yml --check
OK, http://omega.library.yorku.ca is accessible using the credentials provided.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /home/nruest/Projects/york/test-content/workbench-pipe-issue/entity/entity.csv found.
OK, all 1 rows in the CSV file have the same number of columns as there are headers (18).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, term IDs/names in CSV file exist in their respective taxonomies.
OK, files named in the CSV "file" column are all present.
Configuration and input data appear to be valid.
```

run
```
./workbench --config config.yml
```

log
```
07-Oct-20 08:09:00 - INFO - Starting configuration check for "create" task using config file config.yml.
07-Oct-20 08:09:00 - INFO - http://omega.library.yorku.ca is accessible using the credentials provided.
07-Oct-20 08:09:00 - INFO - OK, configuration file has all required values (did not check for optional values).
07-Oct-20 08:09:00 - INFO - OK, CSV file /home/nruest/Projects/york/test-content/workbench-pipe-issue/entity/entity.csv found.
07-Oct-20 08:09:00 - INFO - OK, all 1 rows in the CSV file have the same number of columns as there are headers (18).
07-Oct-20 08:09:01 - INFO - OK, CSV column headers match Drupal field names.
07-Oct-20 08:09:01 - INFO - OK, required Drupal fields are present in the CSV file.
07-Oct-20 08:09:04 - INFO - OK, term IDs/names in CSV file exist in their respective taxonomies.
07-Oct-20 08:09:04 - INFO - OK, files named in the CSV "file" column are all present.
07-Oct-20 08:09:04 - INFO - Configuration checked for "create" task using config file config.yml, no problems found.
07-Oct-20 08:09:09 - INFO - "Create" task started using config file config.yml
07-Oct-20 08:09:11 - ERROR - Node for CSV record 1127680 not created, HTTP response code was 422.
```

## Long text :yellow_square: 
longtext.csv
```csv
"field_pid","file","field_member_of","field_display_hints","id","field_model","title","field_extent","field_genre","field_edtf_date","field_linked_agent","field_subject","field_language","field_rights","field_note","field_identifier","field_local_identifier","field_resource_type"
"yul:1127652","yul_1127652.tif",15,2,1127680,25,"Montage workshop. no.29","1 photograph : b&w negative ; 35 mm.",32,1981,"relators:pht:31",33,38,"http://rightsstatements.org/vocab/InC/1.0/","Funding: Material digitized as part of an Academic Innovation Fund (AIF), Digital Humanities and Social Sciences (DHSS) for Teaching & Learning awarded in Phase 2 of the program in 2017-2018. For more information see: http://aifprojects.yorku.ca/funded-phase-2/dhss-for-teaching-learning. | Holding: Original in the custody of creator.","29 CERLAC","0029CERLAC",12
```

config.yml
```yml
task: create
host: "http://omega.library.yorku.ca"
username: admin
password: no
content_type: islandora_object
input_dir: /home/nruest/Projects/york/test-content/workbench-pipe-issue/longtext
input_csv: longtext.csv
media_use_tid: 17
drupal_filesystem: "fedora://"
delimiter: ","
subdelimiter: "|"
id_field: id
log_file_path: longtext.log
media_types:
  - file: ['tif', 'tiff', 'jp2', 'zip', 'tar']
  - document: ['pdf', 'doc', 'docx', 'ppt', 'pptx']
  - image: ['png', 'gif', 'jpg', 'jpeg']
  - audio: ['mp3', 'wav', 'aac']
  - video: ['mp4']
  - extracted_text: ['txt']
```

check
```
OK, http://omega.library.yorku.ca is accessible using the credentials provided.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /home/nruest/Projects/york/test-content/workbench-pipe-issue/longtext/longtext.csv found.
OK, all 1 rows in the CSV file have the same number of columns as there are headers (18).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, term IDs/names in CSV file exist in their respective taxonomies.
OK, files named in the CSV "file" column are all present.
Configuration and input data appear to be valid.
```

run
```
Node for "Montage workshop. no.29" (record 1127680) created at http://omega.library.yorku.ca/node/149.
+File media for yul_1127652.tif created.
```

log
```
07-Oct-20 08:22:29 - INFO - Starting configuration check for "create" task using config file config.yml.
07-Oct-20 08:22:29 - INFO - http://omega.library.yorku.ca is accessible using the credentials provided.
07-Oct-20 08:22:29 - INFO - OK, configuration file has all required values (did not check for optional values).
07-Oct-20 08:22:29 - INFO - OK, CSV file /home/nruest/Projects/york/test-content/workbench-pipe-issue/longtext/longtext.csv found.
07-Oct-20 08:22:29 - INFO - OK, all 1 rows in the CSV file have the same number of columns as there are headers (18).
07-Oct-20 08:22:30 - INFO - OK, CSV column headers match Drupal field names.
07-Oct-20 08:22:30 - INFO - OK, required Drupal fields are present in the CSV file.
07-Oct-20 08:22:33 - INFO - OK, term IDs/names in CSV file exist in their respective taxonomies.
07-Oct-20 08:22:33 - INFO - OK, files named in the CSV "file" column are all present.
07-Oct-20 08:22:33 - INFO - Configuration checked for "create" task using config file config.yml, no problems found.
07-Oct-20 08:23:18 - INFO - "Create" task started using config file config.yml
07-Oct-20 08:23:20 - INFO - Node for Montage workshop. no.29 (record 1127680) created at http://omega.library.yorku.ca/node/149.
07-Oct-20 08:24:14 - INFO - Media (file) created at http://omega.library.yorku.ca/media/407, linked to node http://omega.library.yorku.ca/node/149.
07-Oct-20 08:24:14 - INFO - File media for yul_1127652.tif created.
```

![Screenshot from 2020-10-07 08-24-28](https://user-images.githubusercontent.com/218561/95331532-24b6f580-0878-11eb-9e75-9de830cdc88f.png)

## Text

text.csv
```csv
"field_pid","file","field_member_of","field_display_hints","id","field_model","title","field_extent","field_genre","field_edtf_date","field_linked_agent","field_subject","field_language","field_rights","field_note","field_identifier","field_local_identifier","field_resource_type"
"yul:1127652","yul_1127652.tif",15,2,1127680,25,"Montage workshop. no.29","1 photograph : b&w negative ; 35 mm.",32,1981,"relators:pht:31",33,38,"http://rightsstatements.org/vocab/InC/1.0/ | https://creativecommons.org/licenses/by-nc/4.0/","Holding: Original in the custody of creator.","29 CERLAC","0029CERLAC",12
```

config.yml
```yml
task: create
host: "http://omega.library.yorku.ca"
username: admin
password: no
content_type: islandora_object
input_dir: /home/nruest/Projects/york/test-content/workbench-pipe-issue/text
input_csv: text.csv
media_use_tid: 17
drupal_filesystem: "fedora://"
delimiter: ","
subdelimiter: "|"
id_field: id
log_file_path: text.log
media_types:
  - file: ['tif', 'tiff', 'jp2', 'zip', 'tar']
  - document: ['pdf', 'doc', 'docx', 'ppt', 'pptx']
  - image: ['png', 'gif', 'jpg', 'jpeg']
  - audio: ['mp3', 'wav', 'aac']
  - video: ['mp4']
  - extracted_text: ['txt']
```

check
```
./workbench --config config.yml --check
OK, http://omega.library.yorku.ca is accessible using the credentials provided.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /home/nruest/Projects/york/test-content/workbench-pipe-issue/text/text.csv found.
OK, all 1 rows in the CSV file have the same number of columns as there are headers (18).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, term IDs/names in CSV file exist in their respective taxonomies.
OK, files named in the CSV "file" column are all present.
Configuration and input data appear to be valid.
```

run
```
./workbench --config config.yml
Node for "Montage workshop. no.29" (record 1127680) created at http://omega.library.yorku.ca/node/150.
+File media for yul_1127652.tif created.
```

log
```
cat text.log
07-Oct-20 08:27:13 - INFO - Starting configuration check for "create" task using config file config.yml.
07-Oct-20 08:27:14 - INFO - http://omega.library.yorku.ca is accessible using the credentials provided.
07-Oct-20 08:27:14 - INFO - OK, configuration file has all required values (did not check for optional values).
07-Oct-20 08:27:14 - INFO - OK, CSV file /home/nruest/Projects/york/test-content/workbench-pipe-issue/text/text.csv found.
07-Oct-20 08:27:14 - INFO - OK, all 1 rows in the CSV file have the same number of columns as there are headers (18).
07-Oct-20 08:27:15 - INFO - OK, CSV column headers match Drupal field names.
07-Oct-20 08:27:15 - INFO - OK, required Drupal fields are present in the CSV file.
07-Oct-20 08:27:18 - INFO - OK, term IDs/names in CSV file exist in their respective taxonomies.
07-Oct-20 08:27:18 - INFO - OK, files named in the CSV "file" column are all present.
07-Oct-20 08:27:18 - INFO - Configuration checked for "create" task using config file config.yml, no problems found.
07-Oct-20 08:27:33 - INFO - "Create" task started using config file config.yml
07-Oct-20 08:27:35 - INFO - Node for Montage workshop. no.29 (record 1127680) created at http://omega.library.yorku.ca/node/150.
07-Oct-20 08:28:29 - INFO - Media (file) created at http://omega.library.yorku.ca/media/410, linked to node http://omega.library.yorku.ca/node/150.
07-Oct-20 08:28:29 - INFO - File media for yul_1127652.tif created.
```

![Screenshot from 2020-10-07 08-28-06](https://user-images.githubusercontent.com/218561/95331554-297ba980-0878-11eb-91bb-fdabdc83e2c9.png)
