### ISSUE TITLE
Provide default values for media_types

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#175]
```
media_types:
 - file: ['tif', 'tiff', 'jp2', 'zip', 'tar']
 - document: ['pdf', 'doc', 'docx', 'ppt', 'pptx']
 - image: ['png', 'gif', 'jpg', 'jpeg']
 - audio: ['mp3', 'wav', 'aac']
 - video: ['mp4']
 - extracted_text: ['txt']
```
is pretty ugly. Those values would be acceptable as defaults, as long as users could overrride them.
