### ISSUE TITLE
media_types config option should override, not replace, defaults. 

### ISSUE THREAD

**Issue by rosiel** [mjordan/islandora_workbench#334]
Follow up on https://github.com/mjordan/islandora_workbench/issues/78:

I bunch of files of different types, and one of them has a file extension that is not hard-coded into , so the documentation page requires me to convert a HTML table of workbench's defaults into the following YAML format:

```
media_types:
  - image: ["png", "gif", "jpg", "jpeg"]
  - document: ["pdf", "doc", "docx", "ppt", "pptx"]
  - file: ["tif", "tiff", "jp2", "zip", "tar"]
  - audio: ["mp3", "wav", "aac"]
  - video: ["mp4"]
  - extracted_text: ["txt"]
```

before adding it to config along with adding my own. This is kind of obnoxious! Without regular expressions the typing is some sort of after-school punishment. Can we either put that above blob of YAML in the documentation to avoid forcing users to hand-do the arduous reformatting, or better yet, make it so that I can do:

```
media_types: - audio: ["m4a"] 
```

and that leave the existing mappings in place while providing that file extension override?
