### ISSUE TITLE
Windows reading unicode off of Google sheet causes error during `--check`

### ISSUE THREAD

**Issue by yamyyao** [mjordan/islandora_workbench#366]
When using a Google sheet as a input CSV file on Windows, certain characters cause an error during `--check`.

Here's the [Google sheet](https://docs.google.com/spreadsheets/d/1DV0Ka0ZafZq3RgCn0x_AetFtlmnMuNFltzck2QL0ApY/edit?usp=sharing), where the cell G28 is causing issues with the value of "தொகுதி 1 - தொடக்கத்தில்".

The output is
```
OK, connection to Drupal at https://islandora.traefik.me verified.
OK, configuration file has all required values (did not check for optional values).
Extracting CSV data from https://docs.google.com/spreadsheets/d/1DV0Ka0ZafZq3RgCn0x_AetFtlmnMuNFltzck2QL0ApY/edit?usp=sharing (worksheet gid 994664908) to ../repo_islandora_demo_objects\google_sheet.csv.
OK, CSV file ../repo_islandora_demo_objects\google_sheet.csv found.
Error: Row 27 (ID 19) of the CSV file "../repo_islandora_demo_objects\google_sheet.csv" has more columns (18) than there are headers (18).
```

This error doesn't appear if the cell is replaced with English characters. This error also doesn't appear when using a local CSV with the same values.

#### config.yml

```yml
task: create
host: "https://islandora.traefik.me"
input_csv: 'https://docs.google.com/spreadsheets/d/1DV0Ka0ZafZq3RgCn0x_AetFtlmnMuNFltzck2QL0ApY/edit?usp=sharing'
google_sheets_gid: 994664908
input_dir: ../repo_islandora_demo_objects
allow_missing_files: true
additional_files:
- Transcript: 7
- Supplemental_PDF: 2
allow_adding_terms: true
```
