### ISSUE TITLE
`--check` doesn't respect `allow_missing_files: true`

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/islandora_workbench#434]
When running `--check` on a CSV with missing files and a config with `allow_missing_files: true` the check is still exiting early.

Config:
```yml
task: create
host: "http://dams.library.unlv.edu"
username: REDACTED
password: 'REDACTED'
input_dir: 'O:\digitalworkspace\MAN Manuscript Collections'
input_csv: MS-00169.csv 
allow_missing_files: true
content_type: dc_object
id_field: field_digital_id
additional_files:
    - service: 139
```
Run:
```
> python3 workbench --config MS-00169.yml --check
OK, connection to Drupal at http://dams.library.unlv.edu verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file O:\digitalworkspace\MAN Manuscript Collections\MS-00169.csv found.
OK, all 1438 rows in the CSV file have the same number of columns as there are headers (36).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, link field values in the CSV file validate.
OK, EDTF field values in the CSV file validate.
Error: CSV row with ID man000750 contains an empty "file" value.
```

This diff resolves the issue:
```diff
diff --git a/workbench_utils.py b/workbench_utils.py
index 5738b83..b5c05c6 100644
--- a/workbench_utils.py
+++ b/workbench_utils.py
@@ -1343,7 +1343,7 @@ def check_input(config, args):
             # Check for empty 'file' values.
             if len(file_check_row['file']) == 0:
                 message = 'CSV row with ID ' + file_check_row[config['id_field']] + ' contains an empty "file" value.'
-                if config['exit_on_first_missing_file_during_check'] is True:
+                if config['exit_on_first_missing_file_during_check'] is True and config['allow_missing_files'] is False:
                     logging.error(message)
                     sys.exit('Error: ' + message)
                 else:
@@ -1356,7 +1356,7 @@ def check_input(config, args):
                 if http_response_code != 200 or ping_remote_file(config, file_check_row['file']) is False:
                     message = 'Remote file "' + file_check_row['file'] + '" identified in CSV "file" column for record with ID "' \
                         + file_check_row[config['id_field']] + '" not found or not accessible (HTTP response code ' + str(http_response_code) + ').'
-                    if config['exit_on_first_missing_file_during_check'] is True:
+                    if config['exit_on_first_missing_file_during_check'] is True and config['allow_missing_files'] is False:
                         logging.error(message)
                         sys.exit('Error: ' + message)
                     else:
```
