### ISSUE TITLE
Add media task --check won't run, just hangs

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#477]
I am attempting to run an add_media task. When running --check, nothing happens in terminal - it just hangs. Am I doing something wrong? I haven't done an add_media task in a while, so I'm wondering if it's user error. I did define several "additional files" in my configuration file - maybe that messed things up? I also tried with and without defining an input directory and the same problem happened both times. I followed the instructions here, since I'm adding multiple different file types: https://mjordan.github.io/islandora_workbench_docs/adding_multiple_media/.

Here's my terminal (after 7 minutes):
```
islandora@trislandora2-production:/opt/islandora_workbench$ ./workbench --config add_mediaPROD.yml --check

```
Config file:
```
task: add_media
host: "https://digitalcollections-i2-prod.tricolib.brynmawr.edu/"
username: [myusername]
password: [mypassword]
input_dir: /mnt/ingest
input_csv: PROD_AddMedia.csv
allow_missing_files: true
additional_files:
 - screenshot: 38
 - transcript: 40
 - thumbnail: 39
 - full_text: 228
```

CSV is attached.
[PROD_AddMedia.csv](https://github.com/mjordan/islandora_workbench/files/9708631/PROD_AddMedia.csv)
