### ISSUE TITLE
Convert integration tests to use ISLE, not the Playbook

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#487]
Since ISLE appears to be the preferred method of running an Islandora instance locally, tests should use it, and not the Playbook, as their target Drupal.

Currently, all integration tests use the following values in their config files:

```yaml
host: "http://localhost:8000"
username: admin
password: islandora
```

They should use:

```yaml
host: https://islandora.traefik.me/
username: admin
password: password
```
These credentials assume that the ISLE "secrets" are not enabled.
