### ISSUE TITLE
Feature Request: Username lookup instead of uid

### ISSUE THREAD

**Issue by seth-shaw-asu** [mjordan/islandora_workbench#614]
Optionally use a user name instead of uid in spreadsheets. Our staff are in the habit of adding user IDs (e.g. sshaw28) instead of their uid to spreadsheets.

**Comment by mjordan** [comment]
Makes total sense since you can use term names.

**Comment by mjordan** [comment]
@seth-shaw-asu can you check out the issue_614 branch and test this work so far?

First, install this View:

```yaml
uuid: 4e118cf7-7b44-46cf-ada4-d0a0081ee785
langcode: en
status: true
dependencies:
  module:
    - rest
    - serialization
    - user
id: uid_from_username
label: 'UID from username'
module: views
description: ''
tag: ''
base_table: users_field_data
base_field: uid
display:
  default:
    id: default
    display_title: Default
    display_plugin: default
    position: 0
    display_options:
      fields:
        name:
          id: name
          table: users_field_data
          field: name
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: user
          entity_field: name
          plugin_id: field
          label: ''
          exclude: false
          alter:
            alter_text: false
            make_link: false
            absolute: false
            word_boundary: false
            ellipsis: false
            strip_tags: false
            trim: false
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: user_name
          settings: {  }
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      pager:
        type: mini
        options:
          offset: 0
          items_per_page: 10
          total_pages: null
          id: 0
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      access:
        type: perm
        options:
          perm: 'access user profiles'
      cache:
        type: tag
        options: {  }
      empty: {  }
      sorts: {  }
      arguments:
        name:
          id: name
          table: users_field_data
          field: name
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: user
          entity_field: name
          plugin_id: string
          default_action: default
          exception:
            value: all
            title_enable: false
            title: All
          title_enable: false
          title: ''
          default_argument_type: query_parameter
          default_argument_options:
            query_param: username
            fallback: ''
            multiple: and
          default_argument_skip_url: false
          summary_options:
            base_path: ''
            count: true
            override: false
            items_per_page: 25
          summary:
            sort_order: asc
            number_of_records: 0
            format: default_summary
          specify_validation: false
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          glossary: false
          limit: 0
          case: none
          path_case: none
          transform_dash: false
          break_phrase: false
      filters:
        status:
          id: status
          table: users_field_data
          field: status
          entity_type: user
          entity_field: status
          plugin_id: boolean
          value: '1'
          group: 1
          expose:
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
      style:
        type: serializer
      row:
        type: fields
        options:
          default_field_elements: true
          inline: {  }
          separator: ''
          hide_empty: false
      query:
        type: views_query
        options:
          query_comment: ''
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_tags: {  }
      relationships: {  }
      header: {  }
      footer: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - request_format
        - url
        - url.query_args
        - user.permissions
      tags: {  }
  rest_export_1:
    id: rest_export_1
    display_title: 'REST export'
    display_plugin: rest_export
    position: 1
    display_options:
      pager:
        type: none
        options:
          offset: 0
      style:
        type: serializer
        options:
          uses_fields: false
          formats:
            json: json
      row:
        type: data_entity
        options: {  }
      display_extenders:
        matomo:
          enabled: false
          keyword_gets: ''
          keyword_behavior: first
          keyword_concat_separator: ' '
          category_behavior: none
          category_gets: ''
          category_concat_separator: ' '
          category_fallback: ''
          category_facets: {  }
          category_facets_concat_separator: ', '
      path: uid_from_username
      auth:
        - basic_auth
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - request_format
        - url
        - user.permissions
      tags: {  }
```
And include user names instead of user IDs in your `create` or `update` task CSV like this:

```csv
file,uid,id,title,field_model
IMG_1410.tif,admin,01,Small boats in Havana Harbour,Image
IMG_Image49.jp2,mark,02,Manhatten Island,Image
IMG_2940.JPG,03,admin,Looking across Burrard Inlet,Image
IMG_2958.JPG,admin,04,Amsterdam waterfront,Image
IMG_5083.JPG,mark,05,Alcatraz Island,Image
```

**Comment by mjordan** [comment]
@seth-shaw-asu can you give this a smoketest when you get a chance?

**Comment by seth-shaw-asu** [comment]
Sorry I let this fall through the cracks. I'll test it today.

**Comment by seth-shaw-asu** [comment]
I copied and pasted the view you provided and attempted a load, but REST doesn't like it. I tried both with 'admin' and a 'test' user:

```
01-Nov-23 17:21:38 - INFO - GET http://localhost:8000/user/admin?_format=json
01-Nov-23 17:21:38 - INFO - {'User-Agent': 'Islandora Workbench'}
01-Nov-23 17:21:38 - INFO - 404
01-Nov-23 17:21:38 - INFO - {"message":"The \u0022user\u0022 parameter was not converted for the path \u0022\/user\/{user}\u0022 (route name: \u0022rest.entity.user.GET\u0022)"}
01-Nov-23 17:21:38 - ERROR - CSV field "uid" in record with ID 01 contains a user ID "admin" that does not exist in the target Drupal.
Error: CSV field "uid" in record with ID 01 contains a user ID "admin" that does not exist in the target Drupal.
...
01-Nov-23 17:26:38 - INFO - GET http://localhost:8000/user/test?_format=json
01-Nov-23 17:26:38 - INFO - {'User-Agent': 'Islandora Workbench'}
01-Nov-23 17:26:38 - INFO - 404
01-Nov-23 17:26:38 - INFO - {"message":"The \u0022user\u0022 parameter was not converted for the path \u0022\/user\/{user}\u0022 (route name: \u0022rest.entity.user.GET\u0022)"}
01-Nov-23 17:26:38 - ERROR - CSV field "uid" in record with ID 01 contains a user ID "test" that does not exist in the target Drupal.
Error: CSV field "uid" in record with ID 01 contains a user ID "test" that does not exist in the target Drupal.
```
Confirmed with curl:
```
$ curl -u 'admin:islandora' -v localhost:8000/user/admin?_format=json
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
* Server auth using Basic with user 'admin'
> GET /user/admin?_format=json HTTP/1.1
> Host: localhost:8000
> Authorization: Basic YWRtaW46aXNsYW5kb3Jh
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Wed, 01 Nov 2023 17:31:43 GMT
< Server: Apache/2.4.52 (Ubuntu)
< X-Powered-By: PHP/8.1.17
< Cache-Control: must-revalidate, no-cache, private
< X-UA-Compatible: IE=edge
< Content-language: en
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Expires: Sun, 19 Nov 1978 05:00:00 GMT
< X-Generator: Drupal 9 (https://www.drupal.org)
< Transfer-Encoding: chunked
< Content-Type: application/json
< 
* Connection #0 to host localhost left intact
{"message":"The \u0022user\u0022 parameter was not converted for the path \u0022\/user\/{user}\u0022 (route name: \u0022rest.entity.user.GET\u0022)"}
```


User entity REST config `rest.resource.entity.user.yml`:
```yml
uuid: 08212569-caeb-4a83-92ec-6ba92549f386
langcode: en
status: true
dependencies:
  module:
    - basic_auth
    - serialization
    - user
_core:
  default_config_hash: 7l1NBsFqG818aOmd_bqTDa_oWi3EpV75Vf4wpkoxppo
id: entity.user
plugin_id: 'entity:user'
granularity: resource
configuration:
  methods:
    - GET
  formats:
    - json
  authentication:
    - basic_auth
```
