### ISSUE TITLE
No such file or directory - validate_fixity_during_check

### ISSUE THREAD

**Issue by Natkeeran** [mjordan/islandora_workbench#644]
If you provide a relative path in the input file, and have the validate_fixity_during_check setting set to true, it throws a file not found error. Absolute path works.   

Seems like the validation logic is getting the file info here, https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L1724.  It is handling the relative path logic.

**Comment by mjordan** [comment]
@Natkeeran I can't replicate this error. Here's my config:

```yaml
task: create
host: https://islandora.traefik.me
username: admin
password: password
input_csv: issue_644.csv
standalone_media_url: true
fixity_algorithm: md5
validate_fixity_during_check: true
```
and my CSV (note both relative and absolute `file` values):

```
file,id,title,field_model,checksum
issue_644_test/IMG_2940.JPG,03,Looking across Burrard Inlet,Image,1ae45027f2e00ebfd986c4ac504351c0
IMG_2958.JPG,04,Amsterdam waterfront,Image,ce7f2d0783a39f3b304cc2ac12ed38b6
/tmp/IMG_5083.JPG,05,Alcatraz Island,Image,2d7c728724c5949b072e7c000eb6a241
```
Running `./workbench --config issue_644.yml --check` works fine. Am I not understanding how to replicate the error?
