### ISSUE TITLE
media_type_file_fields config error

### ISSUE THREAD

**Issue by Natkeeran** [mjordan/islandora_workbench#711]
```
media_types:
 - file: ['zip', 'tar']
 - document: ['pdf', 'doc', 'docx', 'ppt', 'pptx', 'vtt', 'csv']
 - image: ['png', 'gif', 'jpg', 'jpeg', 'tif', 'tiff', 'jp2']
 - audio: ['mp3', 'wav', 'aac', 'm4a']
 - video: ['mp4']
 - extracted_text: ['txt']
 - web_archive: ['wacz']
media_type_file_fields:
 - web_archive: field_media_file
input_dir: input_data/repo_sample_objects
standalone_media_url: true

```

When having this config media_type_file_fields, it is throwing the following error:

```
│   3403 │   │                                                                                     │
│ ❱ 3404 │   │   media_field = config['media_type_file_fields'][media_type]                        │
│   3405 │   │   if media_type in get_oembed_media_types(config):                                  │
│   3406 │   │   │   if 'title' in csv_row:                                                        │
│   3407 │   │   │   │   # WIP on #572: 'title' applies to node CSVs, for media, it should be 'na  │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/ruamel.yaml-0.17.21-py3.10.egg/ruamel/yaml/compat.py:217 │
│ in __getitem__                                                                                   │
│                                                                                                  │
│   214 │   def __getitem__(self, index):                                                          │
│   215 │   │   # type: (Any) -> Any                                                               │
│   216 │   │   if not isinstance(index, slice):                                                   │
│ ❱ 217 │   │   │   return self.__getsingleitem__(index)                                           │
│   218 │   │   return type(self)([self[i] for i in range(*index.indices(len(self)))])  # type:    │
│   219 │                                                                                          │
│   220 │   def __setitem__(self, index, value):                                                   │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/ruamel.yaml-0.17.21-py3.10.egg/ruamel/yaml/comments.py:5 │
│ 27 in __getsingleitem__                                                                          │
│                                                                                                  │
│    524 │                                                                                         │
│    525 │   def __getsingleitem__(self, idx):                                                     │
│    526 │   │   # type: (Any) -> Any                                                              │
│ ❱  527 │   │   return list.__getitem__(self, idx)                                                │
│    528 │                                                                                         │
│    529 │   def __setsingleitem__(self, idx, value):                                              │
│    530 │   │   # type: (Any, Any) -> None                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: list indices must be integers or slices, not str

```

```
commit b38d37e7ec0e606b55e6545b33859708861e533d (HEAD -> main, origin/main, origin/HEAD)
Merge: 3c3f7a8 db790e6
Author: Mark Jordan <mjordan@sfu.ca>
Date:   Mon Oct 30 11:29:05 2023 -0700

    Merge pull request #706 from mjordan/issue_705
    
    Issue 705 and 702

```
