### ISSUE TITLE
Allow users to rerun the same job if any nodes fail to be created

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#749]
I had an interesting question today from a prospective Workbench user: "If some nodes fail to be created, why can't I just fix the problems and rerun the same job again?"

This would allow the user to inspect the log, look for failed nodes, fix the problem in the input, and run the same task again without removing the successful rows from the input CSV or creating a separate CSV for the failed rows. Or, if the problem was a bad connection to Drupal (which sometimes happens), they wouldn't have to change anything. Or, the user could add new rows to the CSV to create additional nodes.

The answer to the prospective user's question could be "yes." We already have the data we need to skip rows in a `create` input CSV that have nodes in Drupal. When a node is created, its node ID and the corresponding CSV "id" value are stored in Workbench's [CSV-to-node-ID map](https://mjordan.github.io/islandora_workbench_docs/generating_csv_files/#using-the-csv-id-to-node-id-map). Logic could be added such that Workbench would skip CSV rows whose "id" values already exist in the map because the nodes they describe were just created in the job that suffered some failures. In other words, during a rerun of a `create` task, Workbench would only create nodes for CSV rows that were not represented in the map, using the CSV "id" value as the lookup key.

Current behavior is to allow reuse of "id"s. That is, non-unique IDs are allowed in the CSV ID to node ID map. If we change this, the logic would be to check for a CSV ID in the map and if it exists, move on to the next CSV row. There is a risk that if IDs were reused across jobs, CSV rows with those non-unique IDs would not get created.

Therefore, we need a way to enforce unique IDs, at least within a limited scope of rerunning a job to pick up failed (or newly added) items.

Options:

- Each entry in the map contains the full path to the `create` task's config file. As a way of scoping which CSV IDs are checked during rerun jobs, Workbench would check to see if the config file path in the map entries is the same as the current config file's path. If it is, Workbench would only check to see if an ID was present in the map if the file path is the same as for existing ids.
     - Assumption is that people change their config filename/path between jobs. Probably a reasonable assumption but would need to be confirmed by asking around.
     - A reasonable requirement for a rerun job would be that the config filename/path would need to be the same as the original task's config file. After all, there would be no need to change the filename if you're just rerunning the same task.
- For rerun jobs, require the user to add a config setting to their file that would make wb skip CSV rows with existing IDs, e.g. "create_missing_nodes_only: true".
    - Risk here is that the user forgets to add it to their config when rerunning a cleanup task.
    - This is my least preferred option.
- Given that the documentation for the 'id' field says "Also note that it is important to use values in this column that are unique across input CSV files if you plan to create parent/child relationships across Workbench sessions.", maybe we should be providing a config setting (and encouraging its use) that prohibits duplicate 'id' values. `--check` would inspect the map to see if any values in the "create" csv exist, and if so, advise the user to add a new setting "allow_duplicate_csv_id_to_node_id_mappings: true" if they actually want to do this. Note that this would change existing behaviour, but if users want to retain their existing maps, they could add this setting.

In any case, if we support this ability, we may want to encourage the use of the `timestamp_rollback: true` config setting so the rerun job doesn't overwrite the original job's rollback.csv file.

**Comment by mjordan** [comment]
Enforcing unique "id" values in the CSV-ID-to-node-ID map is probably a good idea anyway. We can add a `allow_duplicate_csv_id_to_node_id_mappings` to allow reuse. I will open a separate issue for this.

**Comment by mjordan** [comment]
An alternative to relying on the CSV-ID-to-node_id map is to use Drupal as the source of truth. This can be done by creating a View that uses data from a CSV field, such as `field_local_identifier` to check to see if a node exists, and if so, to skip adding it. This approach might be better than using the map, since it would allow nodes to be created by non-Workbench workflows (e.g. manually via the Drupal GUI).

A new configuration setting like the following would enable this:

```
node_exists_verification_view_endpoint:
  - local_identifier_lookup: field_local_identifier
 ```

Creating the View with a REST endpoint would be up to the user but this is pretty easy do do if documented well.

Of course, this approach assumes that values in the target field are unique, but `--check` could check that.

Here's a View config that does this:

```
uuid: 244b7fc3-fee6-44d3-8907-f3a96ecdf2ab
langcode: en
status: true
dependencies:
  module:
    - node
    - rest
    - serialization
    - user
id: local_identifier_lookup
label: 'Local identifier lookup'
module: views
description: ''
tag: ''
base_table: node_field_data
base_field: nid
display:
  default:
    id: default
    display_title: Default
    display_plugin: default
    position: 0
    display_options:
      fields:
        nid:
          id: nid
          table: node_field_data
          field: nid
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          entity_field: nid
          plugin_id: field
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: number_integer
          settings:
            thousand_separator: ''
            prefix_suffix: true
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      pager:
        type: mini
        options:
          offset: 0
          items_per_page: 10
          total_pages: null
          id: 0
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      access:
        type: perm
        options:
          perm: 'access content'
      cache:
        type: tag
        options: {  }
      empty: {  }
      sorts: {  }
      arguments: {  }
      filters:
        status:
          id: status
          table: node_field_data
          field: status
          entity_type: node
          entity_field: status
          plugin_id: boolean
          value: '1'
          group: 1
          expose:
            operator: ''
        field_local_identifier_value:
          id: field_local_identifier_value
          table: node__field_local_identifier
          field: field_local_identifier_value
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: string
          operator: '='
          value: field_local_identifier
          group: 1
          exposed: true
          expose:
            operator_id: field_local_identifier_value_op
            label: ''
            description: ''
            use_operator: false
            operator: field_local_identifier_value_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: field_local_identifier_value
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              content_editor: '0'
              administrator: '0'
              fedoraadmin: '0'
            placeholder: ''
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
      style:
        type: serializer
      row:
        type: fields
        options:
          default_field_elements: true
          inline: {  }
          separator: ''
          hide_empty: false
      query:
        type: views_query
        options:
          query_comment: ''
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_tags: {  }
      relationships: {  }
      header: {  }
      footer: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - request_format
        - url
        - url.query_args
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }
  rest_export_1:
    id: rest_export_1
    display_title: 'REST export'
    display_plugin: rest_export
    position: 1
    display_options:
      pager:
        type: some
        options:
          offset: 0
          items_per_page: 10
      style:
        type: serializer
        options:
          uses_fields: true
          formats:
            json: json
      row:
        type: data_field
        options:
          field_options:
            title:
              alias: field_local_identifier
              raw_output: false
      display_extenders:
        matomo:
          enabled: false
          keyword_gets: ''
          keyword_behavior: first
          keyword_concat_separator: ' '
          category_behavior: none
          category_gets: ''
          category_concat_separator: ' '
          category_fallback: ''
          category_facets: {  }
          category_facets_concat_separator: ', '
      path: local_identifier_lookup
      auth:
        - basic_auth
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - request_format
        - url
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }
```

and here's the REST request that Workbench would make:

```
curl -v -uadmin:password -H "Content-Type: application/json" "https://islandora.traefik.me/local_identifier_lookup?field_local_identifier_value=sfu_001x"
```

If 'sfu_001x' is in `field_local_identifier`, the result is `[{"nid":"125"}]`. If it's not, the result is `[]`.
