### ISSUE TITLE
Media types should be configurable

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#78]
Currently the `set_media_type(mimetype)` function sets the Drupal media type based on MIME type of the file. Some Islandora instances need more flexibility. For now, we should be able to set the media type in the config file.

**Comment by mjordan** [comment]
One way to do this is to keep (but expand) the current MIME-type detecting, but provide the ability to specify a media type in the config file with overrides and supplements the auto-detect.

**Comment by mjordan** [comment]
7bb868dba1f0f55b5d9d64e12e7bebeda482efbf lets you add `media_type: xxx` to config files for create and add_media tasks. Its value will be used as the media type when creating new media. However, `set_media_type()` needs to be expanded to include the recently added media types 'document' and 'extracted_text'.

**Comment by mjordan** [comment]
The current MIME type guessing needs to be replaced. Islandora 8 1.1.0 defines the following extensions in its media types:

* Extracted text: txt, doc, docx, pdf
* Audio: mp3, wav, aac
* Document: txt, rtf, doc, docx, ppt, pptx, xls, xlsx, pdf, odf, odg, odp, ods, odt, fodt, fods, fodp, fodg, key, numbers, pages
* File: txt, rtf, doc, docx, ppt, pptx, xls, xlsx, pdf, odf, odg, odp, ods, odt, fodt, fods, fodp, fodg, key, numbers, pages, tiff, tif, jp2
* Image: png, gif, jpg, jpeg
* Video: mp4
* Remote video: No extensions, field is a text field (for link to video)

So, for example, the media type for a file with the extension `.pdf` is ambiguous (Document or File?).

A couple of options:

1. We require a field in the CSV that indicates a file's media type.
1. We add a required configuration option that maps extensions to media types. We could provide a standard mapping and allow users to change it if they want.

An example of the second option could be:

```yaml
media_types:
 - file: ['zip', 'tar']
 - document: ['pdf', 'doc', 'docx', 'ppt', 'pptx']
 - image: ['png', 'gif', 'jpg', 'jpeg']
 - audio: ['mp3', 'wav', 'aac']
 - video: ['mp4']
 - extracted_text: ['txt']
```
