### ISSUE TITLE
Spreadsheet Editor

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/islandora_workbench#8]
For bulk-editing/creating records our staff would like a spreadsheet-like experience with one row per record. Fields with multiple values (e.g. subjects) will need a delimiter. (Our staff are used to the CONTENTdm's semicolon delimiter convention although Drupal's entity autocomplete uses commas.)

There are a number of options out there, as noted by [Fancy Grid's awesome-grid](https://github.com/FancyGrid/awesome-grid), so the question becomes "which one?"

A few features that we would like to see include:
- "fill down" option for quickly duplicating row values
- "read only" cells (so we don't accidentally change node ids when doing updates)
- image display support for showing thumbnails for the item the row corresponds to
- auto-complete (admittedly, we probably won't get this for free, but some sort of plugin support so we can build our own)
- auto-complete/drop-down support for multiple values
- grouping (for complex objects)

Early on I was keen on [Handsontable](https://handsontable.com/), but they recently changed from an MIT license to a commercial license as of version 7.x. I've received confirmation from their sales team that we could use their "non-commercial license key", however we would need to be very clear that the workbench is not 100% open source and can't be re-released commercially without paying. We could take the Sakai approach and simply fork their 6.2.2 release (the last using MIT), or rely on [Sakai's fork](https://github.com/sakaicontrib/handsontable).

It may be better to just stick with another open source project. Options I'm considering are [DataTables](https://datatables.net/) and [x-spreadsheet](https://github.com/myliang/x-spreadsheet).

**Comment by seth-shaw-unlv** [comment]
Scratch [DataTables](https://datatables.net/). It requires a paid extension for editing data.

**Comment by mjordan** [comment]
@seth-shaw-unlv excellent feature. This could just write the CSV file out, which workbench could then use.

**Comment by seth-shaw-unlv** [comment]
Current contender is [jExcel](https://bossanova.uk/jexcel/v3/) ([MIT license](https://github.com/paulhodel/jexcel/blob/v3.0.1/LICENSE)).

**Comment by mjordan** [comment]
@seth-shaw-unlv this will get you all the terms in a vocabulary (here using the `islandora_models` vocab as our example):

`curl -H 'Accept: application/vnd.api+json'  http://admin:islandora@localhost:8000/jsonapi/taxonomy_term/islandora_models`
 
The editor UI could populate pick lists from these values.

**Comment by seth-shaw-unlv** [comment]
@mjordan can the ingester take a base64 encoded jpeg as a column value (to populate a thumbnail)? jExcel can store an image in base64 as a cell value which is useful for metadata creators as they work with a large spreadsheet view of items. We could have the workbench generate thumbnails from the master files it finds and populate the spreadsheet with them.

**Comment by mjordan** [comment]
So instead of a filename, the cell value would be a base64 string? I don't see why not, as long as the string was escaped for CSV. Then, when it comes time to do the ingest, workbench could use something like [this](https://stackoverflow.com/questions/12315398/verify-is-a-string-is-encoded-in-base64-python) to detect if the cell value is base64 and if so decode it for pushing up into Islandora.

**Comment by seth-shaw-unlv** [comment]
The cell value would look something like `data:image/jpeg;base64,/9j/4AAQSkZJRgAB...`. So, basically, if our cell value begins with 'file:' we would expect a directory path but if it begins with 'data:' we would expect a mime-type, semicolon, encoding, comma, then the encoded data.

**Comment by mjordan** [comment]
Could we skip the 'file' for ordinary filenames? Otherwise, users of the command-line tool would need to add that. In other words, only add 'data:' if it's encoded data.

**Comment by seth-shaw-unlv** [comment]
Fine by me. I'm just brainstorming ideas at this point.

**Comment by mjordan** [comment]
I'd like to make the command-line tool usable on its own, without a GUI. But, also I want to make it as easy to fit a GUI on top of as possible. :smile:

**Comment by seth-shaw-unlv** [comment]
It looks like [jExcel](https://bossanova.uk/jexcel/v3/) is going to be a good option. I've created [a repo as a scratch pad](https://github.com/seth-shaw-unlv/islandora-jexcel-scratchpad) to play with how it works until we have the Electron app skeleton in place. 

You can checkout the work in progress by cloning the repo and then opening the spreadsheet.html in your browser. It will even populate a subjects field dropdown if you have an Islandora instance running at localhost:8000 with some subject, geo_location, people, family, and/or corporate_body terms. Clicking the floppy-disk icon will download whatever you have in the spreadsheet as a CSV to your computer.

**Comment by mjordan** [comment]
I will check this out tonight!

**Comment by mjordan** [comment]
Got my CORS configured. Spreadsheet loads well, but I am experiencing some strangeness with my JSON:API. It is suddenly (for no apparent reason) returning a "Some resources have been omitted because of insufficient authorization." message and not allowing the admin user to `GET` stuff. Very strange, and unrelated to your spreadsheet app. Please stand by while I figure this out. Maybe @dannylamb could test in the meantime.

**Comment by mjordan** [comment]
Web Console indicated that the `Access-Control-Allow-Origin` header was missing from my CORS config, so I added it (in `web/sites/default/default.services.yml`), did a `drush cr`, but the error in Web Console remains. Here's the CORS section of my default.services.yml file:

```yaml
   cors.config:
     enabled: true
     # Specify allowed headers, like 'x-allowed-header'.
     allowedHeaders: ['Access-Control-Allow-Origin', 'x-csrf-token','authorization','content-type','accept','origin','x-requested-with']
     # Specify allowed request methods, specify ['*'] to allow all possible ones.
     allowedMethods: ['*']
     # Configure requests allowed from specific origins.
     allowedOrigins: ['*']
     # Sets the Access-Control-Expose-Headers header.
     exposedHeaders: false
     # Sets the Access-Control-Max-Age header.
     maxAge: false
     # Sets the Access-Control-Allow-Credentials header.
     supportsCredentials: false
```

Is there anything else I need to do?
