### ISSUE TITLE
Incorrect CSV Export Labels for Taxonomy Terms Using Views Export

### ISSUE THREAD

**Issue by DonRichards** [mjordan/islandora_workbench#803]
I encountered an issue with the Islandora Workbench when generating a CSV file from a Drupal view, as outlined in the documentation [here](https://mjordan.github.io/islandora_workbench_docs/generating_csv_files/#using-a-drupal-view-to-identify-content-to-export-as-csv).

The issue arises with the export of taxonomy terms. Specifically, the export incorrectly adds "subject:" to many taxonomy terms. For example, the term "Brown, John, 1800-1859" is correctly listed under the "person" taxonomy, but the exported CSV labels it as "subject:person:Brown, John, 1800-1859." 

This causes an error during import: 

```
Error: CSV field "field_subject" in row 35 contains a term ("Brown, John, 1800-1859") that is not in the referenced vocabulary ("subject").
```
<table>
  <tr>
    <td style="border: 1px solid black;">
      <img width="416" alt="Screenshot 2024-07-22 at 2 59 07 PM" src="https://github.com/user-attachments/assets/91671ab9-3c98-42d0-9d1f-6331d69c037b">
    </td>
  </tr>
</table>

The YML that generated this:

```yml
task: get_data_from_view
host: URL
username: admin
password: Password
view_path: '/daily_nodes_created_test'
content_type: islandora_object
export_csv_file_path: islandora_export.csv
secure_ssl_only: false
export_csv_term_mode: name
```

Link to the Json output for the ID throwing the error. https://gist.github.com/DonRichards/05c66bff444b6a122ef8225d7400b11b

This issue appears to be a minor bug, but it disrupts the import process. The workaround is really simple; just do a text find and replace. So this is a very low priority issue since there's a simple work around and the `--check` feature finds and warns about it.
