### ISSUE TITLE
Provide option to infer values for field_display_hints from media entensions/MIME types

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#86]
It would be useful to provide an option to have workbench infer values for `field_display_hints` based on media file extensions. Workbench already provides an option to infer media type from extensions in the `media_types` config option:

```
media_types:
 - file: ['tif', 'tiff', 'jp2', 'zip', 'tar']
 - document: ['pdf', 'doc', 'docx', 'ppt', 'pptx']
 - image: ['png', 'gif', 'jpg', 'jpeg']
 - audio: ['mp3', 'wav', 'aac']
 - video: ['mp4']
 - extracted_text: ['txt']
```

It would be possible to something similar with values of the "Islandora Display" taxonomy. It would be safer if Workbench queried Drupal to get the term IDs since they are not guaranteed to be the same across Islandora instances.
