### ISSUE TITLE
Enable create_terms and update_terms to work with Paragraphs

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#880]
We have some taxonomies that include Paragraphs, and would like to be able to ingest that data onto our site with a Workbench `create_terms` task. Derek asked about this in Slack, and we got this info from Mark:

> Sorry - the logic to handle Paragrph field types is not present in `create_terms` tasks. [This is the code](https://github.com/mjordan/islandora_workbench/blob/main/workbench#L327-L337) for creating Paragraph fields in nodes. It would need to be added to the [equivalent block of logic](https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L6754-L6821) in the `get_term_field_data()` function. I can open an issue to address this if you want, or you can.

We're looking into this here, and are hoping to be able to submit a PR shortly.

**Comment by mjordan** [comment]
Super, thank you. Please include a sample config file and CSV in your PR so I can test.

**Comment by mjordan** [comment]
Or, if you aren't writing an integration test, please send me the sample config and CSV separately.

**Comment by dara2** [comment]
I added the following at line 6768 of workbench_utils.py:
```
# Entity reference revision fields (paragraphs).
            elif (
                vocab_field_definitions[field_name]["field_type"]
                == "entity_reference_revisions"
            ):
                entity_reference_revisions_field = (
                    workbench_fields.EntityReferenceRevisionsField()
                )
                term_field_data = entity_reference_revisions_field.create(
                    config, vocab_field_definitions, term_field_data, term_csv_row, field_name
                )
```
The term gets created (as it did before), but the paragraph data is still not included. I am now seeing this warning in the workbench.log (which is helpful and wasn't there before):
`28-Jan-25 13:53:42 - WARNING - Could not determine target paragraph type for field "field_related_person_paragraph"`

I do have the paragraph type data in the YML, so I'm not sure what I'm missing. Here's my YML:
```
task: create_terms
host: "https://islandoratest.marmot.org/"
username: admin
password: XXX
# input_dir: /mnt/dara
input_csv: MARMOT_RelPersonTest.csv
vocab_id: person
allow_adding_terms: true
validate_terms_exist: false
paragraph_fields:
  node:
    field_related_person_paragraph:
      type: related_person_bundle
      field_order:
        - field_related_person
        - field_related_person_note
      field_delimiter: '^'
      subdelimiter: '|'
```
And my CSV:

[MARMOT_RelPersonTest.csv](https://github.com/user-attachments/files/18578057/MARMOT_RelPersonTest.csv)

**Comment by dara2** [comment]
I'm wondering if something needs to change in my YML where I define the paragraph stuff - like maybe "node" should be something else. I tried `term_field_data` because that's what appears in place of `node` in workbench_utils.py for the taxonomy term creation, but that had the same result (i.e., no paragraph data was ingested, same warning about paragraph type).

**Comment by dara2** [comment]
Got it! I needed to update "node" in the YML to be "taxonomy_term" so now my config looks like this:
```
task: create_terms
host: "https://islandoratest.marmot.org/"
username: admin
password: XXX
# input_dir: /mnt/dara
input_csv: MARMOT_RelPersonTest.csv
vocab_id: person
allow_adding_terms: true
validate_terms_exist: false
#columns_with_term_names:
paragraph_fields:
  taxonomy_term:
    field_related_person_paragraph:
      type: related_person_bundle
      field_order:
        - field_related_person
        - field_related_person_note
      field_delimiter: '^'
      subdelimiter: '|'
```
We'll submit a PR for this tomorrow.
