### ISSUE TITLE
"Check" on update_terms errors out with "KeyError: 'id'" on valid CSVs

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#913]
I am running an update_terms task. The `--check` errored out like this:
```
islandora@islandoraproduction:/mnt/data/islandora_workbench$ ./workbench --config marmot_update_terms.yml --check
OK, connection to Drupal at https://islandoraproduction.marmot.org verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /mnt/data/ingest/sample/MARMOT_Person_Update_022825.csv found.
OK, all 7 rows in the CSV file have the same number of columns as there are headers (22).
OK, CSV column headers match Drupal field names.
OK, link field values in the CSV file validate.
OK, EDTF field values in the CSV file validate.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /mnt/data/islandora_workbench/./workbench:3946 in <module>                   │
│                                                                              │
│   3943 │   │   │   if config["task"] == "create_from_files":                 │
│   3944 │   │   │   │   check_input_for_create_from_files(config, args)       │
│   3945 │   │   │   else:                                                     │
│ ❱ 3946 │   │   │   │   check_input(config, args)                             │
│   3947 except KeyboardInterrupt:                                             │
│   3948 │   print("Exiting before entire --check completed.")                 │
│   3949 │   logging.warning('Workbench exiting after receiving "ctrl-c" durin │
│                                                                              │
│ /mnt/data/islandora_workbench/workbench_utils.py:2934 in check_input         │
│                                                                              │
│    2931 │   │                                                                │
│    2932 │   │   validate_taxonomy_field_csv_data = get_csv_data(config)      │
│    2933 │   │   # @todo: add the 'rows_with_missing_files' method of accumul │
│ ❱  2934 │   │   warn_user_about_taxo_terms = validate_taxonomy_field_values( │
│    2935 │   │   │   config, field_definitions, validate_taxonomy_field_csv_d │
│    2936 │   │   )                                                            │
│    2937 │   │   if warn_user_about_taxo_terms is True:                       │
│                                                                              │
│ /mnt/data/islandora_workbench/workbench_utils.py:8101 in                     │
│ validate_taxonomy_field_values                                               │
│                                                                              │
│    8098 │   │   │   │   │   field_definitions,                               │
│    8099 │   │   │   │   │   column_name,                                     │
│    8100 │   │   │   │   │   row[column_name],                                │
│ ❱  8101 │   │   │   │   │   row[config["id_field"]],                         │
│    8102 │   │   │   │   )                                                    │
│    8103 │   │   │   │   new_term_names_in_csv_results.append(new_term_names_ │
│    8104                                                                      │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'id'
```
But when I ran the update, it went through without a problem.
My CSV (which includes a `term_id` column) is here:

[MARMOT_Person_Update_022825.csv](https://github.com/user-attachments/files/19032548/MARMOT_Person_Update_022825.csv)

The config is:
```
task: update_terms
host: "https://islandoraproduction.marmot.org"
username: xxx
password: xxx
input_dir: /mnt/data/ingest/sample
input_csv: MARMOT_Person_Update_022825.csv
vocab_id: person
update_mode: append
allow_adding_terms: true
validate_terms_exist: false
paragraph_fields:
 taxonomy_term:
   field_related_person_paragraph:
     type: related_person_bundle
     field_order:
       - field_related_person
       - field_related_person_note
     field_delimiter: '^'
     subdelimiter: '|'
```
