### ISSUE TITLE
make_local_tests.py breaks the config files

### ISSUE THREAD

**Issue by whikloj** [mjordan/islandora_workbench#918]
If you run `make_local_tests.py` with `--password` it replaces "password" in the various configuration files. 

Unfortunately those files by default look something like
`./tests/assets/check_test/create.yml`
```yaml
task: create
host: https://islandora.dev
username: admin
password: password
secure_ssl_only: false
```

And after running something like
```bash
python3 scripts/make_local_tests.py --host http://islandora.traefik.me --user workbench_user --password workbench_password
```
they look like
```yaml
task: create
host: https://islandora.dev
username: admin
workbench_password: workbench_password
secure_ssl_only: false
```
