### ISSUE TITLE
Automate PDF Generation and Release Upload for islandora_workbench_docs

### ISSUE THREAD

**Issue by DonRichards** [mjordan/islandora_workbench#934]
## Description:

We should automate the generation of a PDF version of our MkDocs documentation and upload it to GitHub on every merge to main. This will help us distribute the docs in a portable format and make it easier for users to access offline. To be frank, I'm trying to get the docs to index on a few different LLMs and this would vastly improve my workflows. 

Tasks:
	•	Install mkdocs-pdf-export-plugin or alternative tool for PDF generation
	•	Configure mkdocs.yml to support PDF export
	•	Create a GitHub Actions workflow that:
	•	Runs on push to main
	•	Installs dependencies (mkdocs, mkdocs-print-site-plugin, etc.)
	•	Builds the MkDocs site
	•	Exports the documentation as a PDF
	•	Uploads the PDF as an artifact or release asset

Intended Criteria:
	•	On each merge to main, a PDF is generated from the latest docs
	•	The PDF is attached to a GitHub Release or stored as a downloadable artifact

Let’s use the latest-pdf tag or similar for the release to always reflect the most current version.

### 🛠️ High-Level Steps:

1. **Install a PDF plugin/tool in your MkDocs build**  
   You can use [mkdocs-exporter](https://github.com/adrienbrignon/mkdocs-exporter) or [mkdocs-print-site-plugin](https://github.com/timvink/mkdocs-print-site-plugin) to generate PDFs.

2. **Add a GitHub Actions workflow** that:
   - Runs on `push` to `main`
   - Builds the MkDocs site
   - Exports the PDF
   - Uploads it to GitHub as a Release asset or tag artifact

---

### 🔧 Sample GitHub Actions Workflow (`.github/workflows/pdf-build.yml`):

```yaml
name: Build MkDocs PDF

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-pdf-export-plugin  # or your preferred PDF tool
          pip install weasyprint  # if needed

      - name: Build MkDocs site
        run: mkdocs build

      - name: Export PDF
        run: mkdocs pdf-export

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-pdf
          path: site/pdf/document.pdf  # adjust this to your output path

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mkdocs-pdf
          path: ./release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-pdf
          name: "Latest PDF"
          files: ./release-assets/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

---
