### ISSUE TITLE
Support additional_files configuration in Export tasks

### ISSUE THREAD

**Issue by alxp** [mjordan/islandora_workbench#941]
I needed this capability for a separate project I'm working on, so I'm going to make a PR for this feature shortly as I have it working in my Workbench fork.

## Problem / Motivation

The export_csv and get_data_from_view tasks currently only support exporting one file from each node.

I propose adding the capibility to export all of the other media associated with a given node into the spreadsheet in a format that can then be re-ingested into another Islandora site via a Workbench import.

## Proposed solution

The additional_files configuration option's formatting is already suitable for this.

So a configuration file for a View export would look like this:

```yaml
task: get_data_from_view
host: "http://islandora.test:8080/"
view_path: '/admin/all-islandora-objects'
username: admin
password: islandora
content_type: islandora_object
export_csv_file_path: islandora_export.csv
export_csv_term_mode: name
#export_file_directory: 'exported_files'
secure_ssl_only: False
additional_files:
  - extracted: http://pcdm.org/use#ExtractedText

  -   service: http://pcdm.org/use#ServiceFile
  - thumbnail: http://pcdm.org/use#ThumbnailImage
node_post_export:
  - /Users/aoneill/dev/islandora_workbench/printargs.sh
```

### Tests

There is currently no integration test for get_data_from_view since it would require a specific view to exist.

However there is an existing test for adding additional files that is a good basis for a export_csv task test, which would be helpful for this feature.
