### ISSUE TITLE
"Check" process doesn't recognize jpg as an Image; tries to make it a File and says "jpg" is not an allowed extension

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#961]
Both Derek and I have run into an issue during the --check process where Workbench doesn't recognize a jpg as an Image media type. Instead it treats it as a File media type and says "jpg" is not an allowed extension for File media types. This is happening when WB is pinging a file on an i7 server during the --check process.

Example from my CSV:
[PCUSA-Batch-1_ForIngest-FINAL_OR_version_02 - Sheet1.csv](https://github.com/user-attachments/files/20691185/PCUSA-Batch-1_ForIngest-FINAL_OR_version_02.-.Sheet1.csv)

Derek was able to get around this by doing a media type override to specifically state that jpg is an Image media. This seems to be a new issue that has popped up in Workbench recently; we haven't had this problem in the past. 

In the cases where we've run into this, we've had other media type overrides in our .yml files (but they are unrelated to jpg or images).

Here is my yml file:
```
task: create
host: "https://my-site"
username: xxxx
password: xxxx
input_dir: pcusa
input_csv: PCUSA-Batch-1_ForIngest-FINAL_OR_version_02.csv
output_csv: PCUSA-Batch-1_ForIngest-FINAL_OR_version_02-output.csv
allow_missing_files: true
allow_adding_terms: true
perform_soft_checks: true
standalone_media_url: true
output_csv_include_input_csv: true
delete_tmp_upload: true
adaptive_pause: 2
adaptive_pause_threshold: 2.5 
log_term_creation: false
http_cache_storage: memory
http_cache_storage_expire_after: 600
media_types_override:
- file: ['txt', 'tiff', 'tif', 'vtt']
- video: ['mp4', 'avi', 'mpeg', 'mov']
mimetype_extensions:
  'text/vtt': '.vtt'
  'audio/vnd.wave': '.wav'
additional_files:
 - vtt: 9
 - text: 226
 - thumbnail: 8
 ```
